bigquery/runtime/pom.xml, firestore/runtime/pom.xml, pubsub/runtime/pom.xml, spanner/runtime/pom.xml, storage/runtime/pom.xml
Fixes #15
Necessary for Quarkus tooling
=> Add pom.xml description

.github/workflows/build.yml, integration-tests/app-engine/src/main/resources/application.properties, integration-tests/google-cloud-functions/src/main/resources/application.properties, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/resources/application.properties
=> fix: native test configuration

common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/runtime/graal/DefaultHttpTransportFactorySubstitution.java, integration-tests/app-engine/pom.xml, integration-tests/google-cloud-functions/pom.xml, integration-tests/main/pom.xml, integration-tests/pom.xml
=> fix: DefaultHttpTransportFactorySubstitution is not always needed

README.md
With `projectId`, it raise the below exception.
```
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting com.google.cloud.spanner.Spanner org.acme.GreetingResource.spanner
at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364 …
```
=> doc: fix property key for project id

.github/workflows/build.yml
Master has been renamed to main but the workflow file has not been impacted
=> feat: build on main

README.md
=> doc: document how to mock GoogleCloudCredentials

README.md, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpConfiguration.java, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialProducer.java, integration-tests/main/src/main/resources/application.properties
=> possibility to load the base64 encoded authentication file

integration-tests/main/pom.xml
Fixes #104
/cc @aloubyansky 
I also remove the skip release flag as I assume I will need to release the test jar.
=> Publish main tests as test jar

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/FirestoreResourceTest.java
=> Add firestore host-override

integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/SpannerResourceTest.java, spanner/runtime/src/main/java/io/quarkiverse/googlecloudservices/spanner/runtime/SpannerConfiguration.java, spanner/runtime/src/main/java/io/quarkiverse/googlecloudservices/spanner/runtime/SpannerProducer.java
Allow to configure a Spanner emulator host and add an integration test
=> Spanner emulator

common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialProducer.java, docs/modules/ROOT/pages/secretmanager.adoc, secret-manager/README.md
=> Fix ContextNotActiveException with secret manager config source

common/deployment/src/main/java/io/quarkiverse/googlecloudservices/common/deployment/CommonBuildSteps.java
See https://github.com/quarkusio/quarkus/pull/25598
=> fix: native image generation issue

bigquery/deployment/pom.xml, bigquery/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigquery/deployment/BigQueryBuildSteps.java, bigquery/runtime/pom.xml, bom/pom.xml, common/runtime/pom.xml
=> Update libraries bom and fix native isssue

common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpBootstrapConfiguration.java, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialRecorder.java
=> Enabled or not default project-id.

bom/pom.xml
=> Upgrade to GCP libraries 26.1.0 and resolve dependency divergence

bigquery/runtime/src/main/resources/META-INF/quarkus-extension.yaml, bigtable/runtime/src/main/resources/META-INF/quarkus-extension.yaml, firestore/runtime/src/main/resources/META-INF/quarkus-extension.yaml, pubsub/runtime/src/main/resources/META-INF/quarkus-extension.yaml, secret-manager/runtime/src/main/resources/META-INF/quarkus-extension.yaml, spanner/runtime/src/main/resources/META-INF/quarkus-extension.yaml, storage/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Except Firebase admin as it's very new
=> Move all extensions to preview

bom/pom.xml, firebase-admin/deployment/pom.xml, firebase-admin/runtime/pom.xml, pubsub/runtime/pom.xml, storage/deployment/pom.xml, storage/runtime/pom.xml
=> Netty shadded

docs/modules/ROOT/pages/firebase-admin.adoc, firebase-admin/deployment/pom.xml, firebase-admin/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/deployment/FirebaseAdminBuildSteps.java, firebase-admin/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/deployment/authentication/FirebaseAuthConfiguration.java, firebase-admin/runtime/pom.xml, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/authentication/http/DefaultFirebaseIdentityProvider.java, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/authentication/http/FirebaseAuthenticationRequest.java, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/authentication/http/FirebasePrincipal.java, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/authentication/http/FirebaseSecurityAuthMechanism.java, integration-tests/firebase-admin/src/main/java/io/quarkiverse/googlecloudservices/it/firebaseadmin/FirebaseAppResource.java, integration-tests/firebase-admin/src/main/resources/application.properties, integration-tests/firebase-admin/src/test/java/io/quarkiverse/googlecloudservices/it/firebaseadmin/FirebaseAuthorizationResourceTest.java
Don't merge for now. I will add docs, and I need to add configuration as requested in #416.
I have tried to add unit tests as well but for some reason, quarkus will not inject this into classes in integration tests. It works for me when used in test app directly, so I don't know what could cause this.
Closes: #416
=> feature(firebase-admin): added security authentication for firebase

bigquery/runtime/src/main/resources/META-INF/quarkus-extension.yaml, bigtable/runtime/src/main/resources/META-INF/quarkus-extension.yaml, firebase-admin/runtime/src/main/resources/META-INF/quarkus-extension.yaml, firestore/runtime/src/main/resources/META-INF/quarkus-extension.yaml, logging/runtime/src/main/resources/META-INF/quarkus-extension.yaml, secret-manager/runtime/src/main/resources/META-INF/quarkus-extension.yaml, spanner/runtime/src/main/resources/META-INF/quarkus-extension.yaml, storage/runtime/src/main/resources/META-INF/quarkus-extension.yaml
As stated [here](https://github.com/quarkiverse/quarkus-google-cloud-services/pull/439#issuecomment-1573554919), I have added missing parts of config in quarkus-extension.yaml files. This excludes the pubsub since I have added that in the pubsub related #439
=> Added missing config parts in quarkus-extension.yaml files

pom.xml
@loicmathieu forgot about this, sorry for the noise
=> Add missing prefix in scm/connection

docs/modules/ROOT/pages/firestore.adoc, firestore/deployment/pom.xml, firestore/deployment/src/main/java/io/quarkiverse/googlecloudservices/firestore/deployment/FirestoreBuildSteps.java, firestore/deployment/src/main/java/io/quarkiverse/googlecloudservices/firestore/deployment/FirestoreBuildTimeConfig.java, firestore/deployment/src/main/java/io/quarkiverse/googlecloudservices/firestore/deployment/FirestoreDevServiceConfig.java, firestore/deployment/src/main/java/io/quarkiverse/googlecloudservices/firestore/deployment/FirestoreDevServiceProcessor.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/FirestoreResourceTest.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployment/PubSubBuildSteps.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployment/PubSubBuildTimeConfig.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployment/PubSubDevServiceConfig.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployment/PubSubDevServiceProcessor.java
This PR includes the Firestore dev service. Additionally, it renames Pub/Sub to just PubSub in the documentation and simplifies some variable names in the PubSub dev service processor.
=> feature(devservices): added firestore dev service

docs/antora.yml, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java
This will remove the  `Quarkus ` prefix in the documentation title
=> Adjust doc title

firebase-admin/deployment/pom.xml, pom.xml
Also exclude quarkus-vertx-http-dev-ui-resources as it causes dependency issues
=> Upgrade to Quarkus 3.5.0

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java
=> Allow configuring Firestore databaseId

logging/runtime/pom.xml
=> Use the custom gRPC support in the logging extension

bigquery/runtime/src/main/java/io/quarkiverse/googlecloudservices/bigquery/runtime/BigQueryProducer.java, docs/modules/ROOT/pages/bigquery.adoc, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/BigQueryResource.java
=> Produce a BigQueryWriteClient

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java
@loicmathieu Something along these lines?
=> Add configuration property to force usage of emulator credentials.

docs/modules/ROOT/pages/firebase-admin.adoc
Forgot one instance
Fixes https://github.com/quarkiverse/quarkus-google-cloud-services/issues/640
=> Fix doc issue

integration-tests/app-engine/pom.xml, integration-tests/firebase-admin/pom.xml, integration-tests/main/pom.xml, pom.xml
=> Upgrade Quarkus to 3.16.0

docs/modules/ROOT/pages/includes/quarkus-google-cloud-firebase-devservices.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-firebase-devservices_quarkus.google.adoc
Apparently forgot to regenerate some of the docs from #707
=> Missing regenerated docs

.github/workflows/quarkus-snapshot.yaml, pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/PubSubProducer.java
- Needed for https://github.com/quarkiverse/quarkiverse-devops/issues/315
=> Remove yq from quarkus-snapshot.yaml

.github/workflows/quarkus-snapshot.yaml
@loicmathieu quick attempt at fixing the CI Snapshot build.
Just saw the comment in that file that you can trigger it, so I'm gonna need some help here ;)
=> Potential fix for failing CI quarkus snapshot test workflow

.github/workflows/quarkus-snapshot.yaml
@loicmathieu new PR to try fix it
=> Removed caching

.github/workflows/build.yml, .github/workflows/quarkus-snapshot.yaml, firebase-devservices/deployment/pom.xml
@loicmathieu work in progress on fabri8 version
=> Initial version, try run npm install from docker-maven-plugin

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/QuarkusPubSub.java, secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/SecretManagerProducer.java, spanner/runtime/src/main/java/io/quarkiverse/googlecloudservices/spanner/runtime/SpannerProducer.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
Reduces shutdown time for the main IT
=> Add dispose methods for resources so close is called

firebase-devservices/deployment/src/test/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainerCustomConfigTest.java, firebase-devservices/deployment/src/test/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainerIntegrationTest.java
These should work again
closes #754
=> Revert disabled tests

storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageConfiguration.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
=> Added additional config options for Storage closes #552

bigquery/runtime/src/main/java/io/quarkiverse/googlecloudservices/bigquery/runtime/BigQueryConfiguration.java, bigquery/runtime/src/main/java/io/quarkiverse/googlecloudservices/bigquery/runtime/BigQueryProducer.java
=> Allow overriding the BigQuery host to use an emulator

docs/modules/ROOT/pages/includes/quarkus-google-cloud-firebase-admin.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-firebase-admin_quarkus.google.adoc, firebase-admin/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/deployment/FirebaseAdminBuildSteps.java, firebase-admin/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/deployment/authentication/FirebaseAuthConfiguration.java, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/FirebaseSessionCookieManager.java, firebase-admin/runtime/src/main/java/io/quarkiverse/googlecloudservices/firebase/admin/runtime/authentication/FirebaseSessionCookieConfiguration.java
This seems to work (changed the phase from BUILD_TIME to BUILD_AND_RUNTIME_FIXED mostly). No clue why the other version didn't work, so would be great if we can clarify that @loicmathieu
=> Config setup changed so the default value for enabled is picked up correctly

firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainer.java
In case the extension was used as a JAR file, the resource could not correctly be read from the JAR file, as the ZipFileSystem was not automatically created (see https://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html ). This provides a fix for reading the file.
=> Fix reading the Dockerfile resources from a JAR

integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/mock/ApplicationProducerMock.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
Fixed/reimplementation of #711
=> Automatically use NoCredentials in case the emulator host is being connected to.

firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainer.java
- Needed files are extracted from the JAR and moved to a temporary directory
- The docker image is build from the files in the temp dir.
=> Different strategy for building the base image

pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/QuarkusPubSub.java
This allows for more advanced settings to be configured like message ordering, etc while still connecting correctly to the emulator.
=> Add methods to customize the producer being created.

bom/pom.xml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-bigquery.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-bigquery_quarkus.google.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-vertex-ai.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-vertex-ai_quarkus.google.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-vertx-ai.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-vertx-ai_quarkus.google.adoc, docs/modules/ROOT/pages/vertexai.adoc, integration-tests/main/pom.xml, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/VertexAIResource.java, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/VertexAIResourceTest.java, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/mock/ApplicationProducerMock.java, pom.xml, vertx-ai/README.md, vertx-ai/deployment/pom.xml, vertx-ai/deployment/src/main/java/io/quarkiverse/googlecloudservices/vertexai/deployment/VertexAIBuildSteps.java, vertx-ai/pom.xml, vertx-ai/runtime/pom.xml, vertx-ai/runtime/src/main/java/io/quarkiverse/googlecloudservices/vertexai/runtime/VertexAIProducer.java, vertx-ai/runtime/src/main/java/io/quarkiverse/googlecloudservices/vertexai/runtime/VertxAIConfiguration.java, vertx-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> Add support for Vertex AI

integration-tests/main/src/main/resources/application.properties
This reverts commit b9f0adc9a8609165bc99d089119fc6233aae06ea.
=> Revert "Use an old version of the cloud-dsk image as latest has issues"

firebase-devservices/deployment/src/main/resources/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/user-add.sh
Not related to the other issue, but I noticed when running as root, the user-add script failed
=> Fix check on root user, id didnt discover this correctly

bigtable/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigtable/deployment/BigtableDevServiceProcessor.java, firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/FirebaseDevServiceProcessor.java, firebase-devservices/pom.xml, firestore/deployment/src/main/java/io/quarkiverse/googlecloudservices/firestore/deployment/FirestoreDevServiceProcessor.java, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/StorageResourceTest.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployment/PubSubDevServiceProcessor.java, spanner/deployment/src/main/java/io/quarkiverse/googlecloudservices/spanner/deployment/SpannerDevServiceProcessor.java
GlobalDevServicesConfig will be dropped soon.
=> Switch to using DevServicesConfig
