README.md, common/runtime/pom.xml, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpConfiguration.java, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialProducer.java
@loicmathieu Hi Loic, here is the draft PR to support the injected access tokens, but only if the security account file is not available. I just need to make sure that when `quarkus-oidc` is on the classpath, then, with both `IdTokenCredential` and `AccessTokenCredential` being produced, it is the latter which is injected into `TokenCredential`...
Maybe going forward a map of credentials can be introduced, for example, when more than one service is used and one can only work with the service account (`PubSub`), the other one like `BigQuery` should use access token, etc...but this simple PR should do for now.
`quarkus-security` is a very light dependency and it should be OK linking these services with it as it also has other types of credentials which might become useful in time
=> Init the credentials with the access token if no service account file is available

.github/workflows/build.yml, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/NativeFirestoreResourceIT.java
Native test cannot use mocks so we need a real project to run them
=> fix: go back to build only for native

storage/deployment/pom.xml, storage/deployment/src/main/java/io/quarkiverse/googlecloudservices/storage/deployment/StorageBuildSteps.java, storage/runtime/pom.xml
This PR modifies the storage module to rely on the official GCP GraalVM configuration declared here: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support
If this is satisfactory I can move forward with doing this for Pub/Sub as well which is the other service we believe we have mature support for.
For testing - I manually verified that the integration-test app still works.
cc/ @loicmathieu @meltsufin
=> Modify Quarkus Storage extension to rely on official GraalVM configs

pom.xml
Try to upgrade the `libraries-bom` to the latest version.
@loicmathieu - I noticed our Spring Cloud GCP project was able to use the latest `libraries-bom` version with `micrometer-registry-stackdriver`; maybe the latest libraries-bom version resolves the issue that you encountered earlier.
Our output for `mvn dependency:tree` looked like this for us:
```
[ESC[1;34mINFOESC[m] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.4.0:compile
[ESC[1;34mINFOESC[m] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.4.0:compile
[ESC[1;34mINFOESC[m] |  \- io.micrometer:micrometer-core:jar:1.6.1:compile
[ESC[1;34mINFOESC[m] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[ESC[1;34mINFOESC[m] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
// …
```
=> Upgrade libraries-bom version to latest

bigtable/runtime/pom.xml, common/grpc/pom.xml, common/grpc/src/main/java/io/quarkiverse/googlecloudservices/common/grpc/runtime/graal/GoogleApiGaxGrpcSubstitutions.java, common/pom.xml, firestore/runtime/pom.xml, integration-tests/main/src/main/resources/application.properties, pubsub/runtime/pom.xml, spanner/runtime/pom.xml
This fixes native image for bigtable, firestore and spanner
Fixes #67 and #69
=> Move GRPC substitutions to a common lib

bigquery/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigquery/deployment/BigQueryBuildSteps.java, common/deployment/src/main/java/io/quarkiverse/googlecloudservices/common/deployment/CommonBuildSteps.java, common/runtime/pom.xml, pom.xml, spanner/deployment/src/main/java/io/quarkiverse/googlecloudservices/spanner/deployment/SpannerBuildSteps.java, storage/runtime/pom.xml
Hey Loic,
We just released version `0.2.0` of [`google-cloud-graalvm-support`](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support) and added reflection configurations for several new libraries including Spanner, Firestore, BigQuery, Bigtable, etc. The configurations are conditionally added -- so for example, we use the GraalVM SDK to determine whether say Spanner libraries are on the classpath, and only add the Spanner configurations if that is true.
I think our project is now mature enough to start officially supporting the reflection configuration needs for Google libraries as a whole. This PR migrates the quarkus extension to depend on the `google-cloud-graalvm-support` dependency for all the modules.
Testing: I ran the integration test main and was able to verify …
=> Rely on reflection configurations from google-cloud-graalvm-support

integration-tests/main/pom.xml, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/SecretManagerResource.java, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/GoogleServicesResourcesTest.java, pom.xml, secret-manager/README.md, secret-manager/deployment/pom.xml, secret-manager/deployment/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/deployment/SecretManagerBuildSteps.java, secret-manager/pom.xml, secret-manager/runtime/pom.xml, secret-manager/runtime/src/main/resources/META-INF/quarkus-extension.yaml
For my project, I needed Secret Manager support for Quarkus native, so I decided to try to figure it out myself.
This is an implementation heavily inspired by the pubsub- and firestore-implementation. It's also an implementation that's very close to the original Google client library in user experience.
So I'm drafting this to hear your thoughts on it. Totally understand if it's too early.
=> #75: Straight-forward implementation of GCP Secret Manager support

integration-tests/main/pom.xml
Might fix the Ryuk image download failures
@loicmathieu if you could merge this one quickly, that might fix the Ecosystem CI failure we had last night.
=> Upgrade Testcontainers to 1.15.1

pom.xml
Updates the `google-cloud-graalvm-support` version to `0.3.0` after the latest release.
=> Upgrade google-cloud-graalvm-support version

common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialProducer.java, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/SecretManagerResource.java, secret-manager/deployment/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/deployment/SecretManagerBuildSteps.java, secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/SecretManagerProducer.java
Add the Cloud Platform Auth Scope to enable access to Cloud APIs via service accounts. Add Secret Manager producer to demonstrate issue.
It seems like when using service accounts to authenticate, you need the extra step of calling the `.createScoped(..)` in certain cases. This "cloud-platform" scope comes from the [service account docs](https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam). We do this in our [Spring code](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-core/src/main/java/com/google/cloud/spring/core/DefaultCredentialsProvider.java#L95) too.
I'm not sure why you need this when GCP already has the "IAM role" thing, but this was the only way I could get this sample to work. BTW, the service account needs to also have …
=> Add Cloud Platform Auth Scope

README.md, bigquery/runtime/src/main/java/io/quarkiverse/googlecloudservices/bigquery/runtime/BigQueryProducer.java, common/deployment/src/main/java/io/quarkiverse/googlecloudservices/common/deployment/CommonBuildSteps.java, common/runtime/pom.xml, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, integration-tests/app-engine/README.md, integration-tests/app-engine/src/main/resources/application.properties, integration-tests/google-cloud-functions/README.md, integration-tests/google-cloud-functions/src/main/resources/application.properties, integration-tests/main/README.md, integration-tests/main/src/main/resources/application.properties, secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/SecretManagerProducer.java, spanner/runtime/src/main/java/io/quarkiverse/googlecloudservices/spanner/runtime/SpannerProducer.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
- Falback to default project ID from `ServiceOptions.getDefaultProjectId()` when no projectID is set inside `application.properties`.
- Use the default project ID in the various ITs
=> Default project

pom.xml
Latest version 0.4.0 contains some bug fixes including delaying the initialization of `FirestoreImpl` referenced in #90.
=> Upgrade GCP GraalVM support version

integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/StorageResource.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/StorageResourceTest.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageConfiguration.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
resolves #91
Sadly restrictToAnnotatedClass is not yet available (higher quarkus version?), if the global nature is a problem we could use QuarkusTestResources. But imo it's fine.
Google is a bit incosistent about the naming.
Client Library | Configure Endpoint
-- | --
Datastore | setHost(hostport)
Firestore | setHost(hostport)
Spanner | setEmulatorHost(hostport)
Pub/Sub | setChannelProvider with forTarget(hostport) / setEndpoint(endpoint)
Bigtable | setChannelProvider with forTarget(hostport) / setEndpoint(endpoint)
So for datastore I now went with `quarkus.google.cloud.storage.host-override`, similar to `quarkus.sqs.endpoint-override`.
Any feedback appreciated.
=> Allow Storage Host Configuration with Property

bom/pom.xml, pom.xml
Enforcing dependency convergence is a good practice to bring more determinism into end user apps. We have been managing these versions in Camel Quarkus for a while but quarkus-google-cloud-services seems to be a much better place for it. 
threeten, perfmark and conscrypt could even go to `com.google.cloud:libraries-bom`.
=> Enforce dependencyConvergence

bom/pom.xml
This version is compatible with GraalVM 21.2 that will be the new baseline for Quarkus 2.2
=> Upgrade GraalVM native support to 0.5.0

bigquery/runtime/src/main/java/io/quarkiverse/googlecloudservices/bigquery/runtime/BigQueryProducer.java, common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpBootstrapConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/SecretManagerProducer.java, secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSourceProvider.java, spanner/runtime/src/main/java/io/quarkiverse/googlecloudservices/spanner/runtime/SpannerProducer.java, storage/runtime/src/main/java/io/quarkiverse/googlecloudservices/storage/runtime/StorageProducer.java
Fixes #150
@ppalaga can you test this PR to see if it allows to avoid duplicating the projectId between the application.properties and the route ?
I'm curious about how it interact with the default value provided via `ServiceOptions.getDefaultProjectId()` inside our build steps.
=> Make project ID opttional

bom/pom.xml, common/runtime/pom.xml
Hey Loic,
We recently renamed our project `google-cloud-graalvm-support` to `native-image-support` to be more in-line with existing conventions that others have adopted. Updated github repo: https://github.com/GoogleCloudPlatform/native-image-support-java
This PR updates the project to use the new `native-image-support` artifact.
=> Use updated google native-image-support artifact

docs/modules/ROOT/pages/bigquery.adoc, docs/modules/ROOT/pages/bigtable.adoc, docs/modules/ROOT/pages/firestore.adoc, docs/modules/ROOT/pages/pubsub.adoc, docs/modules/ROOT/pages/secretmanager.adoc, docs/modules/ROOT/pages/spanner.adoc, docs/modules/ROOT/pages/storage.adoc, integration-tests/app-engine/pom.xml, integration-tests/main/pom.xml
This is part of the ongoing effort of pushing RESTEasy Reactive as the
default implementation for Quarkus 2.8.
=> Use RESTEasy Reactive as REST implementation in docs and tests

common/grpc/pom.xml
On 22.3, the substitution annotations have been moved from the svm lib to the graal-sdk lib.
=> Support both GraalVM 22.2 and 22.3

README.md, docs/modules/ROOT/nav.adoc
Hello @loicmathieu. I have just noticed that in #336, I had forgotten to list Firebase Admin both in the README and in the docs navbar. I'm sorry about that. This PR aims to improve the docs only.
=> Add Firebase Admin to README and nav

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreConfiguration.java, firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java
This PR adds options to specify custom retry settings for Firestore.
Users can now configure Firestore retry settings through `application.properties` file. Change was tested with simple Quarkus app and I was able to change retry settings with:
```
quarkus.google.cloud.firestore.retry.max-retry-delay=1M
quarkus.google.cloud.firestore.retry.initial-retry-delay=2S
quarkus.google.cloud.firestore.retry.max-attempts=10
```
=> Add option to specify retry settings for Firestore

firebase-admin/README.md
Updated invalid link to docs in README of firebase-admin. The current link leads to a 404 page.
=> Update README.md of Firebase Admin

docs/modules/ROOT/pages/pubsub.adoc, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/pubsub/TopicManager.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/PubSubResourceTest.java, pubsub/deployment/pom.xml, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployement/PubSubBuildSteps.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployement/PubSubBuildTimeConfig.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployement/PubSubDevServiceConfig.java, pubsub/deployment/src/main/java/io/quarkiverse/googlecloudservices/pubsub/deployement/PubSubDevServiceProcessor.java, pubsub/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Hey there!
Just as I promised, I'm presenting the experimental version of first pubsub devservice, which I already had set up and ready to go. 
This specific devservice is based on the test container implementation of a pubsub emulator, and it's not the only one we can work on using test containers. Here are a few more we can use:
- Bigtable
- Datastore
- Firestore
- Spanner
When it comes to Firebase, though, things may get a little bit more challenging. Unfortunately, test containers don't come with a built-in Firebase implementation, so we'll have to build one from scratch via GenericContainer.
~~This devservice doesn't yet include integration tests.~~
Looking forward to hearing your thoughts on this!
=> feature(devservices): added pubsub dev service

logging/deployment/src/main/java/io/quarkiverse/googlecloudservices/logging/deployment/LoggingBuildSteps.java, logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingConfiguration.java, logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandler.java
This resolves #453.
I introduced two new configuration options:
- `enableConsoleLogging`: with this user can enable or disable default Quarkus console logging. By default, this is disabled so that we prevent duplicated logs.
- `logTarget`: with this user can configure the target of the logs: stdour, stderr, or Google Cloud API. It follows a similar approach as in the official Google Java Logging library (we even use their enums to avoid having to add additional boilerplate code).
With this user has the option to configure logging targets as they wish. They can output logs to Cloud Logging API and still use Quarkus console logging or they disable console logging in case they do not need them or they want to avoid duplication of logs (if they host their app on Google Cloud Platform). …
=> Add option to configure GCP logging extension's logging target

common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpDefaultsConfigSourceFactory.java
This is needed because GcpDefaultsConfigSourceFactory is called very early in the application startup
and can thus mess up the OpenTelemetry configuration performed later by Quarkus
Fixes: https://github.com/quarkusio/quarkus/issues/35500
P.S. This pattern is also used in Quarkus code [here](https://github.com/quarkusio/quarkus/blob/1eb8b2d80673abe76b9cced7a1cf491872d22748/extensions/container-image/container-image-jib/deployment/src/main/java/io/quarkus/container/image/jib/deployment/JibProcessor.java#L246-L267).
=> Prevent the usage of OpenTelemetry in GcpDefaultsConfigSourceFactory

bigtable/deployment/pom.xml, bigtable/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigtable/deployment/BigtableBuildSteps.java, bigtable/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigtable/deployment/BigtableBuildTimeConfig.java, bigtable/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigtable/deployment/BigtableDevServiceConfig.java, bigtable/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigtable/deployment/BigtableDevServiceProcessor.java, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/BigtableResource.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/BigtableResourceTest.java
This PR adds devservice for bigtable. Similar to firstore or pubsub emulators.
=> feature(devservices): added bigtable dev service

firestore/runtime/src/main/java/io/quarkiverse/googlecloudservices/firestore/runtime/FirestoreProducer.java, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/FirestoreResource.java, integration-tests/main/src/main/resources/application.properties, integration-tests/main/src/test/java/io/quarkiverse/googlecloudservices/it/FirestoreResourceTest.java
Implementation to use EmulatorCredentials for dev services (unless access-token-enabled = true)
=> EmulatorCredentials when running on dev services

bom/pom.xml, common/grpc/src/main/java/io/quarkiverse/googlecloudservices/common/grpc/runtime/graal/GoogleApiGaxGrpcSubstitutions.java
Replaces https://github.com/quarkiverse/quarkus-google-cloud-services/pull/659.
@loicmathieu 26.45.0 is the version of `libraries-bom` that Camel will be aligned with in the upcoming Quarkus 3.15.0 release.
If possible, It'd be good to get a new release of `quarkus-google-cloud-services` so that we are in alignment with the Google Cloud bits in the Quarkus Platform.
=> Upgrade com.google.cloud:libraries-bom to 26.45.0

logging/deployment/src/main/java/io/quarkiverse/googlecloudservices/logging/deployment/LoggingBuildSteps.java
Register `Severity` enum for reflection so native app builds don't need to do this themselves. This addresses issue [678](https://github.com/quarkiverse/quarkus-google-cloud-services/issues/678).
This has been tested by native building a Quarkus app and verifying that the correct severity levels appear in the GCP logging console.
=> 678: register Severity enum for reflection

logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandler.java, logging/runtime/src/test/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandlerTest.java
These changes address [issue 674](https://github.com/quarkiverse/quarkus-google-cloud-services/issues/674) by ensuring that the span id and sampled properties are set on the `LogEntry.builder` (without these settings it is not possible to exploit the feature of GCP console where a log entry can be used to launch inspection of the trace corresponding to that log (and vice versa).
These changes have been tested in a native-build Quarkus microservice (running Quarkus 3.11.3).
=> Issue 674 gcp logging spaninfo

docs/modules/ROOT/pages/logging.adoc, logging/deployment/src/main/java/io/quarkiverse/googlecloudservices/logging/deployment/LoggingBuildSteps.java, logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LogRecordLabelExtractor.java, logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LogRecordLabelSupplier.java, logging/runtime/src/main/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandler.java, logging/runtime/src/test/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandlerTest.java
This introduces an extension interface `LogRecordLabelExtractor` which can be implemented to allow custom labels to be added to each log entry when logging to gcp.
=> provide an extension mechanism for adding custom labels to gcp logs

docs/modules/ROOT/pages/pubsub.adoc, pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/PubSubConfiguration.java, pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/QuarkusPubSub.java
Dynamically use NoCredentials in case the emulator is used
=> Use NoCredentials in case the emulator host is being connected to

bom/pom.xml, docs/modules/ROOT/pages/includes/quarkus-google-cloud-pubsub.adoc, docs/modules/ROOT/pages/includes/quarkus-google-cloud-pubsub_quarkus.google.adoc, integration-tests/main/src/main/java/io/quarkiverse/googlecloudservices/it/BigtableResource.java, logging/runtime/src/test/java/io/quarkiverse/googlecloudservices/logging/runtime/LoggingHandlerTest.java, pubsub/runtime/src/main/java/io/quarkiverse/googlecloudservices/pubsub/QuarkusPubSub.java
Closes #704
@jamesnetherton before merging it, I would want to know if it would not conflict with Camel Quarkus.
Did you already upgrade to 26.49.0 in Camel Quarkus?
=> Upgrade GCP BOM to 26.50.0

docs/modules/ROOT/pages/firebase-devservices.adoc, firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainer.java, firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseVersionResolver.java
Currently emulators are downloaded on every startup, increasing startup time.
Lets try to avoid that and make the emulator startup way faster
=> Improve test containers startup speed

firebase-devservices/deployment/src/main/java/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/FirebaseEmulatorContainer.java, firebase-devservices/deployment/src/main/resources/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/Dockerfile.base, firebase-devservices/deployment/src/main/resources/io/quarkiverse/googlecloudservices/firebase/deployment/testcontainers/user-add.sh
There was an issue when an already existing group was used in the docker image. The logic tried to re-add the existing group, which of course failed the docker build. This especially manifested after the recent auto-uid-gid change. With this setup, this is fixed, as the logic first checks if the user exists.
Also, I extracted creation of the base image to a Dockerfile. This reduces the Java logic and is more easier to maintain, as it is now just a regular Dockerfile with some build arguments.
Moving the rest of the logic to a Dockerfile didn't seem the way to go, as this is way less straightforward in it logic (way more optional paths).
=> Fixed issue with running as a group already existing in the docker image

docs/modules/ROOT/pages/firebase-devservices.adoc
See the discussion at https://community.atlassian.com/forums/Bitbucket-questions/Unable-to-create-files-from-docker-image-running-inside-the/qaq-p/3079249#U3087794 
On Bitbucket Pipelines, you run into so weird errors (caused by Bitbucket limitations). Not directly obvious when using this plugin, so added docs
=> Add some documentation how to use dev services on Bitbucket
